// ===== KockaSvijet — jezici (bs default + en) =====
const KS = window.KS = {};

KS.STRINGS = {
bs: {
  'menu.play':'Igraj', 'menu.chars':'Izbor lika', 'menu.options':'Opcije', 'menu.about':'O igri',
  'menu.disclaimer':'Fan projekat — nije povezan ni sa jednom kompanijom',
  'ui.back':'Nazad', 'ui.done':'Gotovo', 'ui.yes':'Da', 'ui.no':'Ne', 'ui.on':'Uključeno', 'ui.off':'Isključeno',
  'worlds.title':'Odaberi svijet', 'worlds.new':'Novi svijet', 'worlds.play':'Igraj svijet',
  'worlds.delete':'Obriši', 'worlds.empty':'Nema sačuvanih svjetova. Napravi novi!',
  'worlds.confirmDel':'Klikni još jednom za brisanje!',
  'new.title':'Novi svijet', 'new.name':'Ime svijeta', 'new.seed':'Sjeme (opcionalno, broj ili riječ)',
  'new.create':'Napravi svijet', 'new.defname':'Moj svijet',
  'new.mode':'Mod: ', 'new.type':'Tip: ', 'new.diff':'Težina: ',
  'mode.survival':'Preživljavanje', 'mode.creative':'Kreativni',
  'type.normal':'Normalan', 'type.flat':'Ravan',
  'diff.peace':'Mirno', 'diff.normal':'Normalno',
  'chars.title':'Izaberi svog lika', 'chars.name':'Tvoje ime',
  'opt.title':'Opcije',
  'opt.sec.graphics':'Grafika', 'opt.sec.sound':'Zvuk', 'opt.sec.controls':'Kontrole', 'opt.sec.other':'Ostalo',
  'opt.rd':'Daljina prikaza', 'opt.fov':'Vidno polje (FOV)', 'opt.fog':'Magla', 'opt.clouds':'Oblaci',
  'opt.particles':'Čestice', 'opt.smooth':'Glatko svjetlo', 'opt.bob':'Ljuljanje kamere',
  'opt.master':'Glavna jačina', 'opt.music':'Muzika', 'opt.sfx':'Zvučni efekti',
  'opt.sens':'Osjetljivost miša', 'opt.invertY':'Obrnuta Y osa', 'opt.controls':'Kontrole…',
  'opt.lang':'Jezik / Language', 'opt.fullscreen':'Cijeli ekran',
  'opt.particles.all':'Sve', 'opt.particles.some':'Malo', 'opt.particles.off':'Ništa',
  'ctl.move':'Kretanje', 'ctl.jump':'Skok / plivanje', 'ctl.sneak':'Šunjanje', 'ctl.sprint':'Trčanje',
  'ctl.break':'Razbij blok (drži)', 'ctl.place':'Postavi blok / koristi', 'ctl.inv':'Inventar',
  'ctl.drop':'Baci predmet', 'ctl.hotbar':'Izbor police', 'ctl.wheel':'Točkić miša — izbor police',
  'ctl.persp':'Promjena kamere (1./3. lice)', 'ctl.debug':'Debug info', 'ctl.pause':'Pauza',
  'ctl.fly':'Let (kreativni): 2× Space', 'ctl.flyud':'Let gore/dole: Space / Shift', 'ctl.shot':'Snimak ekrana',
  'load.building':'Gradimo svijet…', 'load.terrain':'Oblikujemo brda i doline…', 'load.light':'Palimo sunce…',
  'load.mesh':'Slažemo kockice…', 'load.almost':'Još malo…',
  'pause.title':'Pauza', 'pause.resume':'Nastavi igru', 'pause.quit':'Sačuvaj i izađi', 'pause.recipes':'Knjiga recepata',
  'death.title':'Umro si!', 'death.respawn':'Ponovo se pojavi',
  'inv.title':'Inventar', 'inv.craft':'Izrada', 'inv.table':'Sto za izradu', 'inv.furnace':'Peć', 'inv.chest':'Kovčeg',
  'inv.creative':'Svi predmeti', 'inv.trash':'Smeće',
  'tab.blocks':'Blokovi', 'tab.nature':'Priroda', 'tab.tools':'Alati', 'tab.food':'Hrana i razno',
  'recipes.craft':'Izrada', 'recipes.smelt':'Topljenje u peći', 'recipes.smeltAny':'+ gorivo (ugalj, daske, balvani…)',
  'toast.saved':'Svijet sačuvan',
  'toast.saveFail':'Greška pri spremanju (nema prostora?)',
  'toast.bed':'Spavanje još ne postoji — preživi noć!',
  'toast.flyOn':'Letenje uključeno', 'toast.flyOff':'Letenje isključeno',
  'toast.screenshot':'Snimak ekrana sačuvan',
  'toast.storage':'Pažnja: spremanje nije dostupno u ovom pregledniku',
  'death.drop':'Tvoje stvari su ispale na mjestu smrti!',
  'about.text':'KockaSvijet je 3D igra gradnje i preživljavanja od kockica.\n\nIstraži beskrajan svijet, kopaj rude, sagradi dom, napravi alate, preživi noć!\n\nSve teksture, zvukovi i muzika nastaju u kodu dok igraš — igra nema nijedan vanjski fajl i radi potpuno offline.\n\nOvo je fan projekat napravljen iz ljubavi prema igrama gradnje. Nije povezan ni sa jednom kompanijom niti igrom.\n\nNapravljeno uz Claude (Anthropic). Sretno i zabavi se! ⛏',
  'hint.craftTable':'Napravi sto za izradu od 4 daske!',
  'time.day':'Dan', 'time.night':'Noć',
},
en: {
  'menu.play':'Play', 'menu.chars':'Choose character', 'menu.options':'Options', 'menu.about':'About',
  'menu.disclaimer':'Fan project — not affiliated with any company',
  'ui.back':'Back', 'ui.done':'Done', 'ui.yes':'Yes', 'ui.no':'No', 'ui.on':'On', 'ui.off':'Off',
  'worlds.title':'Select world', 'worlds.new':'New world', 'worlds.play':'Play world',
  'worlds.delete':'Delete', 'worlds.empty':'No saved worlds. Create one!',
  'worlds.confirmDel':'Click again to delete!',
  'new.title':'New world', 'new.name':'World name', 'new.seed':'Seed (optional, number or word)',
  'new.create':'Create world', 'new.defname':'My world',
  'new.mode':'Mode: ', 'new.type':'Type: ', 'new.diff':'Difficulty: ',
  'mode.survival':'Survival', 'mode.creative':'Creative',
  'type.normal':'Normal', 'type.flat':'Flat',
  'diff.peace':'Peaceful', 'diff.normal':'Normal',
  'chars.title':'Choose your character', 'chars.name':'Your name',
  'opt.title':'Options',
  'opt.sec.graphics':'Graphics', 'opt.sec.sound':'Sound', 'opt.sec.controls':'Controls', 'opt.sec.other':'Other',
  'opt.rd':'Render distance', 'opt.fov':'Field of view (FOV)', 'opt.fog':'Fog', 'opt.clouds':'Clouds',
  'opt.particles':'Particles', 'opt.smooth':'Smooth lighting', 'opt.bob':'View bobbing',
  'opt.master':'Master volume', 'opt.music':'Music', 'opt.sfx':'Sound effects',
  'opt.sens':'Mouse sensitivity', 'opt.invertY':'Invert Y axis', 'opt.controls':'Controls…',
  'opt.lang':'Jezik / Language', 'opt.fullscreen':'Fullscreen',
  'opt.particles.all':'All', 'opt.particles.some':'Few', 'opt.particles.off':'None',
  'ctl.move':'Move', 'ctl.jump':'Jump / swim', 'ctl.sneak':'Sneak', 'ctl.sprint':'Sprint',
  'ctl.break':'Break block (hold)', 'ctl.place':'Place block / use', 'ctl.inv':'Inventory',
  'ctl.drop':'Drop item', 'ctl.hotbar':'Hotbar select', 'ctl.wheel':'Mouse wheel — hotbar select',
  'ctl.persp':'Toggle camera (1st/3rd person)', 'ctl.debug':'Debug info', 'ctl.pause':'Pause',
  'ctl.fly':'Fly (creative): 2× Space', 'ctl.flyud':'Fly up/down: Space / Shift', 'ctl.shot':'Screenshot',
  'load.building':'Building the world…', 'load.terrain':'Shaping hills and valleys…', 'load.light':'Turning on the sun…',
  'load.mesh':'Stacking the blocks…', 'load.almost':'Almost there…',
  'pause.title':'Paused', 'pause.resume':'Back to game', 'pause.quit':'Save and quit', 'pause.recipes':'Recipe book',
  'death.title':'You died!', 'death.respawn':'Respawn',
  'inv.title':'Inventory', 'inv.craft':'Crafting', 'inv.table':'Crafting table', 'inv.furnace':'Furnace', 'inv.chest':'Chest',
  'inv.creative':'All items', 'inv.trash':'Trash',
  'tab.blocks':'Blocks', 'tab.nature':'Nature', 'tab.tools':'Tools', 'tab.food':'Food & misc',
  'recipes.craft':'Crafting', 'recipes.smelt':'Smelting (furnace)', 'recipes.smeltAny':'+ fuel (coal, planks, logs…)',
  'toast.saved':'World saved',
  'toast.saveFail':'Save failed (storage full?)',
  'toast.bed':'No sleeping yet — survive the night!',
  'toast.flyOn':'Flying enabled', 'toast.flyOff':'Flying disabled',
  'toast.screenshot':'Screenshot saved',
  'toast.storage':'Warning: saving is not available in this browser',
  'death.drop':'Your items dropped where you died!',
  'about.text':'KockaSvijet ("CubeWorld") is a 3D block building & survival game.\n\nExplore an endless world, mine ores, build a home, craft tools, survive the night!\n\nAll textures, sounds and music are generated by code at runtime — the game has zero external files and works fully offline.\n\nThis is a fan project made out of love for building games. Not affiliated with any company or game.\n\nMade with Claude (Anthropic). Have fun! ⛏',
  'hint.craftTable':'Craft a crafting table from 4 planks!',
  'time.day':'Day', 'time.night':'Night',
},
};

// Imena blokova/predmeta — poseban prostor ('blk.<id>' se traži prvo)
KS.STRINGS.bs.names = {
  grass:'Trava', dirt:'Zemlja', stone:'Kamen', cobble:'Kamenčuga', bedrock:'Temeljac',
  sand:'Pijesak', sandstone:'Pješčar', gravel:'Šljunak', water:'Voda', lava:'Lava',
  log:'Hrastov balvan', logBirch:'Brezin balvan', logSpruce:'Smrekov balvan',
  planks:'Daske', planksBirch:'Brezine daske', leaves:'Lišće', leavesSpruce:'Smrekovo lišće',
  glass:'Staklo', coalOre:'Ruda uglja', ironOre:'Željezna ruda', goldOre:'Zlatna ruda', diamondOre:'Dijamantska ruda',
  ironBlock:'Blok željeza', goldBlock:'Blok zlata', diamondBlock:'Blok dijamanta',
  brick:'Cigle', stoneBrick:'Kamene cigle', mossyCobble:'Mahovinasta kamenčuga', obsidian:'Opsidijan',
  snowGrass:'Snježna trava', snow:'Snijeg', ice:'Led', cactus:'Kaktus',
  tnt:'TNT', craftTable:'Sto za izradu', furnace:'Peć', chest:'Kovčeg', torch:'Baklja', glowstone:'Sjajni kamen',
  bookshelf:'Polica s knjigama', flowerRed:'Crveni cvijet', flowerYellow:'Žuti cvijet', tallgrass:'Visoka trava',
  woolWhite:'Bijela vuna', woolRed:'Crvena vuna', woolOrange:'Narandžasta vuna', woolYellow:'Žuta vuna',
  woolGreen:'Zelena vuna', woolBlue:'Plava vuna', woolPurple:'Ljubičasta vuna', woolBlack:'Crna vuna',
  stick:'Štap', coal:'Ugalj', ironIngot:'Željezni ingot', goldIngot:'Zlatni ingot', diamond:'Dijamant',
  apple:'Jabuka', porkRaw:'Sirova svinjetina', porkCooked:'Pečena svinjetina',
  beefRaw:'Sirova govedina', beefCooked:'Biftek', flesh:'Trulo meso',
  swordWood:'Drveni mač', swordStone:'Kameni mač', swordIron:'Željezni mač', swordGold:'Zlatni mač', swordDiamond:'Dijamantski mač',
  pickWood:'Drveni pijuk', pickStone:'Kameni pijuk', pickIron:'Željezni pijuk', pickGold:'Zlatni pijuk', pickDiamond:'Dijamantski pijuk',
  axeWood:'Drvena sjekira', axeStone:'Kamena sjekira', axeIron:'Željezna sjekira', axeGold:'Zlatna sjekira', axeDiamond:'Dijamantska sjekira',
  shovelWood:'Drvena lopata', shovelStone:'Kamena lopata', shovelIron:'Željezna lopata', shovelGold:'Zlatna lopata', shovelDiamond:'Dijamantska lopata',
};
KS.STRINGS.en.names = {
  grass:'Grass', dirt:'Dirt', stone:'Stone', cobble:'Cobblestone', bedrock:'Bedrock',
  sand:'Sand', sandstone:'Sandstone', gravel:'Gravel', water:'Water', lava:'Lava',
  log:'Oak log', logBirch:'Birch log', logSpruce:'Spruce log',
  planks:'Planks', planksBirch:'Birch planks', leaves:'Leaves', leavesSpruce:'Spruce leaves',
  glass:'Glass', coalOre:'Coal ore', ironOre:'Iron ore', goldOre:'Gold ore', diamondOre:'Diamond ore',
  ironBlock:'Iron block', goldBlock:'Gold block', diamondBlock:'Diamond block',
  brick:'Bricks', stoneBrick:'Stone bricks', mossyCobble:'Mossy cobblestone', obsidian:'Obsidian',
  snowGrass:'Snowy grass', snow:'Snow', ice:'Ice', cactus:'Cactus',
  tnt:'TNT', craftTable:'Crafting table', furnace:'Furnace', chest:'Chest', torch:'Torch', glowstone:'Glowstone',
  bookshelf:'Bookshelf', flowerRed:'Red flower', flowerYellow:'Yellow flower', tallgrass:'Tall grass',
  woolWhite:'White wool', woolRed:'Red wool', woolOrange:'Orange wool', woolYellow:'Yellow wool',
  woolGreen:'Green wool', woolBlue:'Blue wool', woolPurple:'Purple wool', woolBlack:'Black wool',
  stick:'Stick', coal:'Coal', ironIngot:'Iron ingot', goldIngot:'Gold ingot', diamond:'Diamond',
  apple:'Apple', porkRaw:'Raw porkchop', porkCooked:'Cooked porkchop',
  beefRaw:'Raw beef', beefCooked:'Steak', flesh:'Rotten flesh',
  swordWood:'Wooden sword', swordStone:'Stone sword', swordIron:'Iron sword', swordGold:'Golden sword', swordDiamond:'Diamond sword',
  pickWood:'Wooden pickaxe', pickStone:'Stone pickaxe', pickIron:'Iron pickaxe', pickGold:'Golden pickaxe', pickDiamond:'Diamond pickaxe',
  axeWood:'Wooden axe', axeStone:'Stone axe', axeIron:'Iron axe', axeGold:'Golden axe', axeDiamond:'Diamond axe',
  shovelWood:'Wooden shovel', shovelStone:'Stone shovel', shovelIron:'Iron shovel', shovelGold:'Golden shovel', shovelDiamond:'Diamond shovel',
};

KS.SPLASHES = [
  '100% kockasto!', 'Pazi se noći!', 'Kopaj duboko!', 'Napravljeno kodom!', 'I dijamanti postoje!',
  'Bez ijednog fajla!', 'Sagradi nešto veliko!', 'Drvo prvo, uvijek!', 'Oprez: TNT!', 'Sve je od kockica!',
  'Radi i offline!', 'Pozdrav iz dubina!', 'Sunce izlazi na istoku!', 'Prasići su prijatelji!',
  'Probaj kreativni mod!', 'Beskrajan svijet!', 'Šta ćeš sagraditi?', 'Baklje tjeraju mrak!',
];

KS.langId = 'bs';
KS.t = function (key) {
  const L = KS.STRINGS[KS.langId] || KS.STRINGS.bs;
  return L[key] !== undefined ? L[key] : (KS.STRINGS.bs[key] !== undefined ? KS.STRINGS.bs[key] : key);
};
KS.tName = function (nameKey) {
  const L = KS.STRINGS[KS.langId] || KS.STRINGS.bs;
  return (L.names && L.names[nameKey]) || KS.STRINGS.bs.names[nameKey] || nameKey;
};
KS.setLang = function (id) {
  KS.langId = KS.STRINGS[id] ? id : 'bs';
  document.querySelectorAll('[data-t]').forEach(el => { el.textContent = KS.t(el.getAttribute('data-t')); });
};
